import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "@/app/globals.css";
import type { User } from "@/app/interfaces/user";
import { UserProvider } from "@/app/contexts/userContext";
import { getProfile } from "@/app/api/api";
import { CookiesProvider } from 'next-client-cookies/server';

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Abricot.co",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user: User | null = await getProfile();

  return (
    <html lang="fr">
      <body className={`${inter.variable} ${manrope.variable} antialiased justify-center flex`}>
        <UserProvider initialUser={user}>
          <CookiesProvider>{children}</CookiesProvider>
        </UserProvider>
      </body>
    </html>
  );
}
